import type { Grade, Question, Student, Badge } from "./types"

export const GRADES: Grade[] = [
  {
    id: 6,
    label: "Lớp 6",
    description: "Số tự nhiên, phân số, hình học trực quan",
    topics: [
      { id: "6-sohoc", name: "Số học & Số tự nhiên", category: "Số học", questionCount: 24 },
      { id: "6-phanso", name: "Phân số & Số thập phân", category: "Số học", questionCount: 18 },
      { id: "6-hinhhoc", name: "Hình học trực quan", category: "Hình học", questionCount: 15 },
      { id: "6-thongke", name: "Dữ liệu & Xác suất", category: "Thống kê", questionCount: 12 },
    ],
  },
  {
    id: 7,
    label: "Lớp 7",
    description: "Số hữu tỉ, biểu thức đại số, tam giác",
    topics: [
      { id: "7-sohuuti", name: "Số hữu tỉ", category: "Đại số", questionCount: 20 },
      { id: "7-bieuthuc", name: "Biểu thức đại số", category: "Đại số", questionCount: 22 },
      { id: "7-tamgiac", name: "Tam giác", category: "Hình học", questionCount: 19 },
      { id: "7-xacsuat", name: "Xác suất thống kê", category: "Xác suất", questionCount: 14 },
    ],
  },
  {
    id: 8,
    label: "Lớp 8",
    description: "Hằng đẳng thức, phân thức, tứ giác",
    topics: [
      { id: "8-hangdangthuc", name: "Hằng đẳng thức đáng nhớ", category: "Đại số", questionCount: 26 },
      { id: "8-phanthuc", name: "Phân thức đại số", category: "Đại số", questionCount: 21 },
      { id: "8-tugiac", name: "Tứ giác & Đa giác", category: "Hình học", questionCount: 18 },
      { id: "8-xacsuat", name: "Xác suất của biến cố", category: "Xác suất", questionCount: 13 },
    ],
  },
  {
    id: 9,
    label: "Lớp 9",
    description: "Căn bậc hai, hàm số bậc hai, đường tròn",
    topics: [
      { id: "9-canbac2", name: "Căn bậc hai", category: "Đại số", questionCount: 28 },
      { id: "9-hamso", name: "Hàm số bậc nhất & bậc hai", category: "Đại số", questionCount: 24 },
      { id: "9-hethucluong", name: "Hệ thức lượng trong tam giác", category: "Hình học", questionCount: 20 },
      { id: "9-duongtron", name: "Đường tròn", category: "Hình học", questionCount: 17 },
    ],
  },
]

export const QUESTIONS: Question[] = [
  {
    id: "q1",
    gradeId: 9,
    topicId: "9-canbac2",
    difficulty: "Thông hiểu",
    prompt: "Rút gọn biểu thức sau:",
    promptLatex: "\\sqrt{48} - \\sqrt{27} + \\sqrt{12}",
    options: [
      { key: "A", text: "", latex: "3\\sqrt{3}" },
      { key: "B", text: "", latex: "\\sqrt{3}" },
      { key: "C", text: "", latex: "5\\sqrt{3}" },
      { key: "D", text: "", latex: "2\\sqrt{3}" },
    ],
    correct: "A",
    solution: "Ta đưa các căn về cùng một dạng căn bậc hai của 3.",
    solutionLatex:
      "\\sqrt{48}-\\sqrt{27}+\\sqrt{12}=4\\sqrt{3}-3\\sqrt{3}+2\\sqrt{3}=3\\sqrt{3}",
  },
  {
    id: "q2",
    gradeId: 9,
    topicId: "9-canbac2",
    difficulty: "Nhận biết",
    prompt: "Điều kiện xác định của biểu thức bên dưới là gì?",
    promptLatex: "\\sqrt{2x - 6}",
    options: [
      { key: "A", text: "", latex: "x \\le 3" },
      { key: "B", text: "", latex: "x \\ge 3" },
      { key: "C", text: "", latex: "x > 0" },
      { key: "D", text: "", latex: "x \\ne 3" },
    ],
    correct: "B",
    solution: "Biểu thức dưới căn phải không âm.",
    solutionLatex: "2x - 6 \\ge 0 \\Leftrightarrow x \\ge 3",
  },
  {
    id: "q3",
    gradeId: 9,
    topicId: "9-hamso",
    difficulty: "Vận dụng",
    prompt: "Cho hàm số bậc nhất. Tìm giá trị của hàm số tại x = 2:",
    promptLatex: "y = f(x) = 3x - 5",
    options: [
      { key: "A", text: "", latex: "f(2) = 1" },
      { key: "B", text: "", latex: "f(2) = -1" },
      { key: "C", text: "", latex: "f(2) = 11" },
      { key: "D", text: "", latex: "f(2) = 6" },
    ],
    correct: "A",
    solution: "Thay x = 2 vào công thức hàm số.",
    solutionLatex: "f(2) = 3 \\cdot 2 - 5 = 6 - 5 = 1",
  },
  {
    id: "q4",
    gradeId: 9,
    topicId: "9-hethucluong",
    difficulty: "Vận dụng cao",
    prompt: "Tam giác vuông ABC vuông tại A có đường cao AH. Hệ thức nào đúng?",
    options: [
      { key: "A", text: "", latex: "AH^2 = AB \\cdot AC" },
      { key: "B", text: "", latex: "AH^2 = HB \\cdot HC" },
      { key: "C", text: "", latex: "AB^2 = BC \\cdot HC" },
      { key: "D", text: "", latex: "AH = HB + HC" },
    ],
    correct: "B",
    solution: "Trong tam giác vuông, bình phương đường cao bằng tích hai hình chiếu.",
    solutionLatex: "AH^2 = HB \\cdot HC",
  },
  {
    id: "q5",
    gradeId: 9,
    topicId: "9-canbac2",
    difficulty: "Thông hiểu",
    prompt: "Tính giá trị của biểu thức:",
    promptLatex: "\\sqrt{(\\sqrt{5} - 3)^2}",
    options: [
      { key: "A", text: "", latex: "\\sqrt{5} - 3" },
      { key: "B", text: "", latex: "3 - \\sqrt{5}" },
      { key: "C", text: "", latex: "\\sqrt{5} + 3" },
      { key: "D", text: "", latex: "8" },
    ],
    correct: "B",
    solution: "Vì căn 5 nhỏ hơn 3 nên giá trị tuyệt đối đổi dấu.",
    solutionLatex: "\\sqrt{(\\sqrt{5}-3)^2} = |\\sqrt{5}-3| = 3 - \\sqrt{5}",
  },
  {
    id: "q6",
    gradeId: 9,
    topicId: "9-hamso",
    difficulty: "Nhận biết",
    prompt: "Hàm số nào sau đây là hàm số bậc nhất?",
    options: [
      { key: "A", text: "", latex: "y = x^2 + 1" },
      { key: "B", text: "", latex: "y = \\frac{2}{x}" },
      { key: "C", text: "", latex: "y = -2x + 7" },
      { key: "D", text: "", latex: "y = \\sqrt{x}" },
    ],
    correct: "C",
    solution: "Hàm số bậc nhất có dạng y = ax + b với a khác 0.",
    solutionLatex: "y = ax + b,\\ a \\ne 0 \\Rightarrow y = -2x + 7",
  },
  {
    id: "q7",
    gradeId: 8,
    topicId: "8-hangdangthuc",
    difficulty: "Thông hiểu",
    prompt: "Khai triển hằng đẳng thức:",
    promptLatex: "(x + 3)^2",
    options: [
      { key: "A", text: "", latex: "x^2 + 9" },
      { key: "B", text: "", latex: "x^2 + 6x + 9" },
      { key: "C", text: "", latex: "x^2 + 3x + 9" },
      { key: "D", text: "", latex: "x^2 - 6x + 9" },
    ],
    correct: "B",
    solution: "Áp dụng hằng đẳng thức bình phương của một tổng.",
    solutionLatex: "(x+3)^2 = x^2 + 2 \\cdot x \\cdot 3 + 3^2 = x^2 + 6x + 9",
  },
  {
    id: "q8",
    gradeId: 8,
    topicId: "8-phanthuc",
    difficulty: "Vận dụng",
    prompt: "Rút gọn phân thức sau:",
    promptLatex: "\\frac{x^2 - 4}{x + 2}",
    options: [
      { key: "A", text: "", latex: "x - 2" },
      { key: "B", text: "", latex: "x + 2" },
      { key: "C", text: "", latex: "x^2 - 2" },
      { key: "D", text: "", latex: "\\frac{1}{x-2}" },
    ],
    correct: "A",
    solution: "Phân tích tử thành nhân tử rồi rút gọn.",
    solutionLatex: "\\frac{x^2-4}{x+2} = \\frac{(x-2)(x+2)}{x+2} = x - 2",
  },
  {
    id: "q9",
    gradeId: 7,
    topicId: "7-sohuuti",
    difficulty: "Thông hiểu",
    prompt: "Thực hiện phép tính:",
    promptLatex: "\\frac{2}{3} + \\frac{1}{6}",
    options: [
      { key: "A", text: "", latex: "\\frac{5}{6}" },
      { key: "B", text: "", latex: "\\frac{3}{9}" },
      { key: "C", text: "", latex: "\\frac{1}{2}" },
      { key: "D", text: "", latex: "\\frac{3}{6}" },
    ],
    correct: "A",
    solution: "Quy đồng mẫu số rồi cộng tử số.",
    solutionLatex: "\\frac{2}{3} + \\frac{1}{6} = \\frac{4}{6} + \\frac{1}{6} = \\frac{5}{6}",
  },
  {
    id: "q10",
    gradeId: 6,
    topicId: "6-sohoc",
    difficulty: "Nhận biết",
    prompt: "Tìm bội chung nhỏ nhất của 4 và 6:",
    options: [
      { key: "A", text: "12" },
      { key: "B", text: "24" },
      { key: "C", text: "10" },
      { key: "D", text: "6" },
    ],
    correct: "A",
    solution: "Phân tích ra thừa số nguyên tố rồi lấy BCNN.",
    solutionLatex: "BCNN(4, 6) = 2^2 \\cdot 3 = 12",
  },
  {
    id: "q11",
    gradeId: 9,
    topicId: "9-duongtron",
    difficulty: "Vận dụng",
    prompt: "Đường tròn (O; R) có dây AB. Khoảng cách từ O đến AB là d. Hệ thức đúng:",
    options: [
      { key: "A", text: "", latex: "AB = 2\\sqrt{R^2 - d^2}" },
      { key: "B", text: "", latex: "AB = \\sqrt{R^2 + d^2}" },
      { key: "C", text: "", latex: "AB = R - d" },
      { key: "D", text: "", latex: "AB = 2(R - d)" },
    ],
    correct: "A",
    solution: "Dùng định lý Pytago cho nửa dây cung.",
    solutionLatex: "\\left(\\frac{AB}{2}\\right)^2 + d^2 = R^2 \\Rightarrow AB = 2\\sqrt{R^2 - d^2}",
  },
  {
    id: "q12",
    gradeId: 9,
    topicId: "9-canbac2",
    difficulty: "Vận dụng cao",
    prompt: "Giải phương trình chứa căn:",
    promptLatex: "\\sqrt{x + 1} = 3",
    options: [
      { key: "A", text: "", latex: "x = 8" },
      { key: "B", text: "", latex: "x = 9" },
      { key: "C", text: "", latex: "x = 2" },
      { key: "D", text: "", latex: "x = 10" },
    ],
    correct: "A",
    solution: "Bình phương hai vế với điều kiện x lớn hơn hoặc bằng -1.",
    solutionLatex: "\\sqrt{x+1} = 3 \\Rightarrow x + 1 = 9 \\Rightarrow x = 8",
  },
  {
    id: "q13",
    gradeId: 8,
    topicId: "8-hangdangthuc",
    difficulty: "Thông hiểu",
    prompt: "Phân tích đa thức thành nhân tử:",
    promptLatex: "x^2 - 9",
    options: [
      { key: "A", text: "", latex: "(x-3)(x+3)" },
      { key: "B", text: "", latex: "(x-3)^2" },
      { key: "C", text: "", latex: "(x+3)^2" },
      { key: "D", text: "", latex: "x(x-9)" },
    ],
    correct: "A",
    solution: "Áp dụng hằng đẳng thức hiệu hai bình phương.",
    solutionLatex: "x^2 - 9 = x^2 - 3^2 = (x-3)(x+3)",
  },
  {
    id: "q14",
    gradeId: 7,
    topicId: "7-tamgiac",
    difficulty: "Nhận biết",
    prompt: "Tổng ba góc trong một tam giác bằng:",
    options: [
      { key: "A", text: "", latex: "90^\\circ" },
      { key: "B", text: "", latex: "180^\\circ" },
      { key: "C", text: "", latex: "360^\\circ" },
      { key: "D", text: "", latex: "270^\\circ" },
    ],
    correct: "B",
    solution: "Định lý tổng ba góc trong tam giác.",
    solutionLatex: "\\widehat{A} + \\widehat{B} + \\widehat{C} = 180^\\circ",
  },
  {
    id: "q15",
    gradeId: 9,
    topicId: "9-hamso",
    difficulty: "Vận dụng",
    prompt: "Parabol đi qua gốc tọa độ có phương trình dạng nào?",
    options: [
      { key: "A", text: "", latex: "y = ax^2\\ (a \\ne 0)" },
      { key: "B", text: "", latex: "y = ax + b" },
      { key: "C", text: "", latex: "y = \\frac{a}{x}" },
      { key: "D", text: "", latex: "y = a" },
    ],
    correct: "A",
    solution: "Hàm số bậc hai dạng y = ax^2 có đồ thị là parabol đỉnh O.",
    solutionLatex: "y = ax^2,\\ a \\ne 0",
  },
]

export const BADGES: Badge[] = [
  { id: "b1", name: "Thần đồng Hình Học", description: "Đạt trên 90% các bài Hình học", unlocked: true },
  { id: "b2", name: "Bậc thầy Căn Thức", description: "Hoàn thành 10 bài Căn bậc hai", unlocked: true },
  { id: "b3", name: "Chăm chỉ", description: "Làm bài 7 ngày liên tục", unlocked: true },
  { id: "b4", name: "Vua Tốc Độ", description: "Hoàn thành bài thi dưới 10 phút", unlocked: false },
  { id: "b5", name: "Điểm 10 Tuyệt đối", description: "Đạt điểm tối đa một bài thi", unlocked: false },
  { id: "b6", name: "Nhà Vô địch", description: "Đứng top 1 lớp", unlocked: false },
]

export const STUDENT_PROGRESS = [
  { topic: "Căn bậc hai", percent: 90 },
  { topic: "Hàm số bậc nhất", percent: 78 },
  { topic: "Hệ thức lượng", percent: 45 },
  { topic: "Đường tròn", percent: 62 },
  { topic: "Hằng đẳng thức", percent: 85 },
]

export const STUDENTS: Student[] = [
  {
    id: "s1",
    name: "Nguyễn Minh Anh",
    email: "minhanh@lop9.edu.vn",
    gradeId: 9,
    testsTaken: 24,
    avgScore: 8.6,
    active: true,
    lastActive: "2 giờ trước",
    submissions: [
      { id: "sub1", title: "Đề ôn Căn bậc hai số 3", gradeId: 9, correct: 13, total: 15, score: 8.7, duration: "18 phút", date: "12/06/2026" },
      { id: "sub2", title: "Kiểm tra Hàm số", gradeId: 9, correct: 12, total: 15, score: 8.0, duration: "22 phút", date: "08/06/2026" },
      { id: "sub3", title: "Đề Hệ thức lượng", gradeId: 9, correct: 9, total: 15, score: 6.0, duration: "25 phút", date: "03/06/2026" },
    ],
    mastery: [
      { topic: "Căn bậc hai", percent: 90 },
      { topic: "Hàm số bậc hai", percent: 82 },
      { topic: "Hệ thức lượng", percent: 45 },
      { topic: "Đường tròn", percent: 70 },
    ],
  },
  {
    id: "s2",
    name: "Trần Gia Bảo",
    email: "giabao@lop9.edu.vn",
    gradeId: 9,
    testsTaken: 18,
    avgScore: 7.2,
    active: true,
    lastActive: "Hôm nay",
    submissions: [
      { id: "sub4", title: "Đề ôn Đường tròn", gradeId: 9, correct: 11, total: 15, score: 7.3, duration: "20 phút", date: "11/06/2026" },
      { id: "sub5", title: "Kiểm tra Căn bậc hai", gradeId: 9, correct: 10, total: 15, score: 6.7, duration: "24 phút", date: "05/06/2026" },
    ],
    mastery: [
      { topic: "Căn bậc hai", percent: 67 },
      { topic: "Hàm số bậc hai", percent: 75 },
      { topic: "Hệ thức lượng", percent: 58 },
      { topic: "Đường tròn", percent: 80 },
    ],
  },
  {
    id: "s3",
    name: "Lê Khánh Chi",
    email: "khanhchi@lop8.edu.vn",
    gradeId: 8,
    testsTaken: 21,
    avgScore: 9.1,
    active: true,
    lastActive: "1 ngày trước",
    submissions: [
      { id: "sub6", title: "Đề Hằng đẳng thức nâng cao", gradeId: 8, correct: 14, total: 15, score: 9.3, duration: "16 phút", date: "10/06/2026" },
      { id: "sub7", title: "Phân thức đại số", gradeId: 8, correct: 13, total: 15, score: 8.7, duration: "19 phút", date: "06/06/2026" },
    ],
    mastery: [
      { topic: "Hằng đẳng thức", percent: 95 },
      { topic: "Phân thức", percent: 88 },
      { topic: "Tứ giác", percent: 79 },
    ],
  },
  {
    id: "s4",
    name: "Phạm Đức Duy",
    email: "ducduy@lop7.edu.vn",
    gradeId: 7,
    testsTaken: 12,
    avgScore: 6.4,
    active: false,
    lastActive: "5 ngày trước",
    submissions: [
      { id: "sub8", title: "Số hữu tỉ cơ bản", gradeId: 7, correct: 9, total: 15, score: 6.0, duration: "27 phút", date: "01/06/2026" },
    ],
    mastery: [
      { topic: "Số hữu tỉ", percent: 60 },
      { topic: "Biểu thức đại số", percent: 52 },
      { topic: "Tam giác", percent: 48 },
    ],
  },
  {
    id: "s5",
    name: "Hoàng Thảo Nguyên",
    email: "thaonguyen@lop6.edu.vn",
    gradeId: 6,
    testsTaken: 15,
    avgScore: 7.8,
    active: true,
    lastActive: "3 giờ trước",
    submissions: [
      { id: "sub9", title: "Số tự nhiên & Ước bội", gradeId: 6, correct: 12, total: 15, score: 8.0, duration: "21 phút", date: "09/06/2026" },
      { id: "sub10", title: "Phân số cơ bản", gradeId: 6, correct: 11, total: 15, score: 7.3, duration: "23 phút", date: "04/06/2026" },
    ],
    mastery: [
      { topic: "Số tự nhiên", percent: 85 },
      { topic: "Phân số", percent: 72 },
      { topic: "Hình học trực quan", percent: 68 },
    ],
  },
  {
    id: "s6",
    name: "Vũ Quang Huy",
    email: "quanghuy@lop8.edu.vn",
    gradeId: 8,
    testsTaken: 9,
    avgScore: 5.6,
    active: false,
    lastActive: "1 tuần trước",
    submissions: [
      { id: "sub11", title: "Phân thức đại số", gradeId: 8, correct: 8, total: 15, score: 5.3, duration: "29 phút", date: "30/05/2026" },
    ],
    mastery: [
      { topic: "Hằng đẳng thức", percent: 55 },
      { topic: "Phân thức", percent: 42 },
      { topic: "Tứ giác", percent: 60 },
    ],
  },
  {
    id: "s7",
    name: "Đặng Phương Linh",
    email: "phuonglinh@lop7.edu.vn",
    gradeId: 7,
    testsTaken: 20,
    avgScore: 8.9,
    active: true,
    lastActive: "30 phút trước",
    submissions: [
      { id: "sub12", title: "Biểu thức đại số nâng cao", gradeId: 7, correct: 14, total: 15, score: 9.3, duration: "17 phút", date: "12/06/2026" },
      { id: "sub13", title: "Tam giác bằng nhau", gradeId: 7, correct: 13, total: 15, score: 8.7, duration: "20 phút", date: "07/06/2026" },
    ],
    mastery: [
      { topic: "Số hữu tỉ", percent: 91 },
      { topic: "Biểu thức đại số", percent: 88 },
      { topic: "Tam giác", percent: 85 },
    ],
  },
  {
    id: "s8",
    name: "Bùi Tuấn Kiệt",
    email: "tuankiet@lop9.edu.vn",
    gradeId: 9,
    testsTaken: 16,
    avgScore: 7.5,
    active: true,
    lastActive: "Hôm qua",
    submissions: [
      { id: "sub14", title: "Đề tổng hợp HK2", gradeId: 9, correct: 11, total: 15, score: 7.3, duration: "26 phút", date: "10/06/2026" },
    ],
    mastery: [
      { topic: "Căn bậc hai", percent: 78 },
      { topic: "Hàm số bậc hai", percent: 70 },
      { topic: "Đường tròn", percent: 74 },
    ],
  },
]
